### ISSUE TITLE
Remove mentions of ESP

### ISSUE THREAD

**Issue by chris-wood** [ietf-tapswg/draft-ietf-taps-transport-security#103]
We collapsed IKEv2 and ESP into IPsec. Should we remove ESP from feature lists, e.g., the list of protocols that support PSK import?

**Comment by renghardt** [comment]
Agreed, we should make sure this is consistent.

One of our features, Key Expiration, currently only mentions ESP though.
Is this actually an IPsec feature now, do we remove the feature, or is there another solution?
