### ISSUE TITLE
Document structure and coverage

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/draft-ietf-taps-transport-security#16]
The protocol description sections don't seem to follow a particular template. It might be helpful to have a standard set of subsections describing features that we want to analyze in the later "common features" section, such as authentication mechanisms, algorithmic agility, transport requirements (e.g., stream vs. datagram, reliability & reordering for datagrams), application interface (e.g., stream vs. message), etc.

The section on common features needs to be fleshed out and individual bullet points made parallel/consistent. One recommendation would be to divide mandatory features from optional features as "those features required for any TAPS application" versus "those features required by SOME TAPS applications", and for the optional features to be phrased as "if your application does X, the transport requires this feature". What I'm thinking is essentially some kind of conceptual decision tree allowing a user to enumerate appropriate transports given the needs of the application.

**Comment by chris-wood** [comment]
@squarooticus I'm closing this since I believe it's done. Please reopen if you feel otherwise!
