### ISSUE TITLE
Feature applicability

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/draft-ietf-taps-transport-security#17]
It's probably easier and more consumable to encode the matrix of protocols providing a particular feature as a table.

**Comment by chris-wood** [comment]
I'm assigning this to you, Kyle. Will you have time to take a stab at it?

**Comment by squarooticus** [comment]
Yep, I'll work on it this afternoon.

**Comment by chris-wood** [comment]
Closed by #37.
