### ISSUE TITLE
DTLS issues

### ISSUE THREAD

**Issue by squarooticus** [ietf-tapswg/draft-ietf-taps-transport-security#19]
From Thomas Fossati:

=> Section 3.2.1:
"Starting with DTLS 1.3, a connection identifier extension [...]"

The CID extension is also available in 1.2.

(In 1.3, the CID can be updated mid-session using post-handshake
messages, which is an option you don't have in 1.2, but for the
rest they are the same.)

=> Section 3.2.3:
"The DTLS record protocol explicitly encodes record lengths"

In 1.3, the "short header" (DTLSShortCiphertext) drops the explicit
length.

**Comment by chris-wood** [comment]
Closed via #36.
