### ISSUE TITLE
Nit: Application-layer feature negotiation vs. Configuration extensions 

### ISSUE THREAD

**Issue by philsbln** [ietf-tapswg/draft-ietf-taps-transport-security#56]
I have a little nit regarding the Security Features "Application-layer feature negotiation" vs. "Configuration extensions". Both things are quite similar and may be used interchangeably (with some pain), but I am missing examples  that match the names.

 - Are "QUIC Transport Parameters" realised by a "Configuration extension"?
 - The only example for "Application-layer feature negotiation" I see are ALPN and SNI, which look more like multiplexing-mechanism, as ALPNs more or less replace ports and SNIs replace distinct addresses.

**Comment by tfpauly** [comment]
This particular section of text is now quite different
