### ISSUE TITLE
Nit: Is TCP really a dependency for TLS?

### ISSUE THREAD

**Issue by philsbln** [ietf-tapswg/draft-ietf-taps-transport-security#57]
Is TCP really a dependency for TLS or (as used for other protocol examples) a "TCP like protocol that provides in-order, reliable transport."

**Comment by csperkins** [comment]
If we change this, and we likely should, the DTLS section will need updating too.

**Comment by tfpauly** [comment]
RFC 8446 says:

`the only requirement from the underlying transport is a reliable, in-order data stream`

**Comment by tfpauly** [comment]
Fixed for both TLS and DTLS with 5dfbdd42475b72f56447ed9fa8f7937010421187
