### ISSUE TITLE
QUIC frame vs packet confusion

### ISSUE THREAD

**Issue by csperkins** [ietf-tapswg/draft-ietf-taps-transport-security#60]
In §4.3.1 "These messages are sent in special INITIAL and CRYPTO frames" -- if I read QUIC correctly, there are CRYPTO frames sent in Initial, 0-RTT, or Handshake packets. 

This looks like just a terminology issue, with the rest of the description being correct, but someone with QUIC implementation experience should check.

**Comment by tfpauly** [comment]
Fixed in 9d98ccae0a7a41f3a5b736b4eb36381a576937f3
