### ISSUE TITLE
Remove normative references

### ISSUE THREAD

**Issue by renghardt** [ietf-tapswg/draft-ietf-taps-transport-security#61]
Our current version has a Normative reference to the QUIC TLS, QUIC Transport draft, TAPS API draft, and several others. We probably want these as Informative references.
Looking at the .md file, these references are not explicitly included at the top - perhaps putting in an explicit informative reference will fix this.

**Comment by tfpauly** [comment]
While this is an issue on the current draft, it's already fixed on master with b6d981e33c1a896d5b4c6a0afc534f3dfdbccf99
