### ISSUE TITLE
Restructure document!

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/draft-ietf-taps-transport-security#64]
Proposed outline:

Introduction
- Goals
- Non-goals

 Terminology

Security Protocols (short sentence descriptions, with reference)
- Application-Specific Payload Security (SRTP)
- Application-Agnostic Payload Security  (TLS/DTLS)	
- Transport Security (QUIC/tcpcrypt/MinimalT)
- IP Security (IKEv2/OpenVPN/WireGuard)	

Interface to Transport
- Stream (reliable)
- Datagram message framing (unreliable or not)
- Protocol-specific needs (TCP-ENO)
	
Interface to Applications
- List application knobs, annotate which protocols support

**Comment by renghardt** [comment]
I think we can close this.

**Comment by csperkins** [comment]
Agree
