### ISSUE TITLE
Reliable Byte-Stream Transports

### ISSUE THREAD

**Issue by renghardt** [ietf-tapswg/draft-ietf-taps-transport-security#68]
Comment from Ekr's review of -10:

4.1.  Reliable Byte-Stream Transports

   The following protocols all depend upon running on a transport
   protocol that provides a reliable, in-order stream of bytes.  This is
   typically TCP.

   Application Payload Security Protocols:

   o  TLS

   Transport-Layer Security Protocols:

   o  tcpcrypt

This doesn't seem quite right, as tcpcrypt is run prior to the TCP
reassembly algorithms.

-- 

Reply from Kyle:

If I'm reading you correctly, this is not right. For compatibility with middleboxes, tcpcrypt runs within the TCP bytestream, just like TLS, and requires reassembly before the tcpcrypt TLV record layer can be parsed.

(So can we close this with no action, or did we miss something?)

**Comment by tfpauly** [comment]
@squarooticus can you confirm if we need any action here?
