### ISSUE TITLE
Summary table for 5.1

### ISSUE THREAD

**Issue by renghardt** [ietf-tapswg/draft-ietf-taps-transport-security#70]
Comment from Ekr's review of -10:

5.1.  Pre-Connection Interfaces

   Configuration interfaces are used to configure the security protocols
   before a handshake begins or the keys are negotiated.

This presentation seems pretty hard to follow, in that it's a lot of
work to figure out which in the long list of protocols doesn't have
this property. Maybe a summary table would help?

**Comment by squarooticus** [comment]
Would it make sense to additionally provide clarifying examples for some of the protocols listed for each interface, where they might not be clear? I don't have a strong opinion, but to give an example, the session caching interface for tcpcrypt is very limited while the one for TLS is more capable.
