### ISSUE TITLE
5.1: tcpcrypt and ZRTP

### ISSUE THREAD

**Issue by renghardt** [ietf-tapswg/draft-ietf-taps-transport-security#71]
Comment from Ekr's review of -10:

5.1.  Pre-Connection Interfaces

[…]
Also, I'm not sure you want to omit tcpcrypt here, in that it does
have a way to do external authentication by exporting a session ID.
Also ZRTP allows for some sort of fingerprint-based auth.

tcpcrypt (and I believe ZRTP) both have session caches.

**Comment by csperkins** [comment]
ZRTP uses [short authentication strings](https://tools.ietf.org/html/rfc6189#section-7), compared by the users, as an external authentication mechanism (similar process to the Safety Numbers in Signal, I believe). 

ZRTP does maintain a session cache.

**Comment by renghardt** [comment]
In other words, ZRTP supports interfaces to Authentication Delegation and Session Cache Management, and DTLS-SRTP does not?
