### ISSUE TITLE
5.1: Mention EAP-TLS?

### ISSUE THREAD

**Issue by renghardt** [ietf-tapswg/draft-ietf-taps-transport-security#72]
Comment from Ekr's review of -10:

  o  Authentication Delegation: The application provides access to a
      separate module that will provide authentication, using EAP for
      example.

You don't list TLS, but what about EAP-TLS?

**Comment by renghardt** [comment]
Reading up on EAP and EAP-TLS, it seems to me that not listing TLS there is correct. It seems like TLS does not delegate its authentication to EAP, but EAP uses TLS as an authentication method.
If I'm missing something, please let me know. 

So, it seems to me that we can close this with no action.
Or, to avoid confusion, we could find a different example than EAP. But it seems like IKEv2 can indeed use EAP and I didn't find another good example.

**Comment by tfpauly** [comment]
@theri I agree with you, I think we can close without action.

**Comment by chris-wood** [comment]
Agreed. Closing.
