### ISSUE TITLE
5.1: Text around import

### ISSUE THREAD

**Issue by renghardt** [ietf-tapswg/draft-ietf-taps-transport-security#73]
Comment from Ekr's review of -10:

I'm not following any of the text around import. This direct/explicit
distinction seems arbitrary, and weird for QUIC, because QUIC doesn't
really have explicit import so much as a dependency on a handshake
protocol that must be integrated.

**Comment by tfpauly** [comment]
@chris-wood  can you help on this one?

**Comment by tfpauly** [comment]
Ping @chris-wood?

**Comment by chris-wood** [comment]
We can do this for the export side of things, too.

**Comment by chris-wood** [comment]
Fixed in #85.
