### ISSUE TITLE
5.3: Clarify IKE Mobility events

### ISSUE THREAD

**Issue by renghardt** [ietf-tapswg/draft-ietf-taps-transport-security#76]
Comment from Ekr's review of -10:

   o  Mobility Events: The record protocol can be signaled that it is
      being migrated to another transport or interface due to connection
      mobility, which may reset address and state validation and induce
      state changes such as use of a new Connection Identifier (CID).

How does this work in ESP, actually?

DTLS sort of has this, in that it has a CID, but vague migration rules.

**Comment by tfpauly** [comment]
It may be better to mark this as IKEv2/ESP; it's MOBIKE that supports mobility.

**Comment by renghardt** [comment]
This can be closed now, right?

**Comment by tfpauly** [comment]
Yup!
