### ISSUE TITLE
Address iotdir review feedback

### ISSUE THREAD

**Issue by chris-wood** [ietf-tapswg/draft-ietf-taps-transport-security#87]
Major issues: The document header says that this document is about interfaces
between security protocols and transport services. Yet, later on, I find that
the document is also discussing the interfaces between security protocols and
applications. Perhaps you could add 'applications' to the title -> 'Interaction
Between Applications, Security Protocols, and Transport Services'

Editorial issues:
- Instead of saying 'This protocol obsoletes TCP MD5 "signature" options', can we say 'TCP-AO obsoletes....' to avoid confusion of what is 'this' 
- Please expand 'and IPsec AH [RFC4302]' -> IP Authentication Header 
- Are you talking about cryptographic agility here 'security protocols: confidentiality, privacy protections, and agility.' ? 
- Consider changing 'interface surface exposed '-> interface exposed by'. Otherwise it sounds too similar to attack surface exposed. 
- Expand EAP and reference RFC3748. - Perhaps you could say that Source Address Validation (SAV) to prevent DoS is relevant for protocols that use unreliable transport?

**Comment by tfpauly** [comment]
Regarding the title change, I think we can not change this, as "Transport Services" is by definition the interaction between applications and transports; we're adding security to the mix. The first sentence of the abstract already mentions applications.

**Comment by tfpauly** [comment]
Should be covered by #98
