### ISSUE TITLE
Robert's feedback

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/draft-ietf-taps-transport-security#92]
----------------------------------------------------------------------
COMMENT:
----------------------------------------------------------------------

As incoming AD I found that document really useful and informative - thank you.

As a minor nit, I found the English around the usage of the term "Transport
Services", that I wasn't familiar with prior to reading this document, slightly
tricky to parse in the introduction, particularly because the term isn't
defined until the Terminology in section 3.

E.g. in the second paragraph it isn't clear to me what a "Transport Services
system" real means.  Possibly replace "a Transport Services system may need to
support" with "a Transport Service may need to support"?

Similarly, perhaps change " One of the goals of Transport Services is to define
a common interface for using transport protocols" to " One of the goals of
Transport Service definitions is to define a common interface for using
transport protocols"?

**Comment by renghardt** [comment]
Addressing this issue, I realized that we do not actually define "Transport Services system" anywhere in -arch, or -interface.
I usually take it to just be a synonym of "TAPS implementation".

Initial proposal for this draft (which I would add to Section 3):
"Transport Services system: a software component that exposes an interface to different Transport Services to an application."

Do you agree?

I'm also going to provide more context in the introduction to make the document easier to understand for people not yet familiar with TAPS.
