### ISSUE TITLE
Erik's feedback

### ISSUE THREAD

**Issue by tfpauly** [ietf-tapswg/draft-ietf-taps-transport-security#95]
{Yes}

[nits]

S4.3

* s/Specific,/Specifically,/

* s/a dependencies/a dependency ?/

S5.3

* Does https://tools.ietf.org/html/rfc8446#section-4.6.3 count as supporting
  Key Expiration?  Maybe not because the send is expected to observe the need
  to rekey and do so, rather than something in the record protocol itself.
  Is that a correct reading?

**Comment by tfpauly** [comment]
@chris-wood can you check on the TLS comment?

**Comment by chris-wood** [comment]
I think the answer is "no" to key expiration, for the reason Erik stated. Namely, TLS doesn't say its keys "expired," it says that they've been updated. (I consider expiration a notice to the application that it's basically stuck, whereas TLS explicitly updates its keys and lets the connection move forward.)
